# Generated by Django 5.0.1 on 2024-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
